### ISSUE TITLE
[streaming output] Support for ComfyUI LLM node in BizyAir

### ISSUE THREAD

**Issue by Bobbyztz** [siliconflow/BizyAir#78]
Hi, I'm also working on building LLMs-centered node in ComfyUI, like Dify/Coze in ComfyUI. Is it possible to support streaming output for LLMs nodes?

Seems like the non-Asynchronous feature of ComfyUI doesn't allow us to do that.

**Comment by doombeaker** [comment]
Thank you for your suggestion. I think stream output is a very practical feature. I assume it can be achieved under the ComfyUI framework by handling it in the js plugin code. However, I'm not certain and need to practice writing frontend js in ComfyUI.
Due to plans for other features, we will not be working on this particular feature in the short term. If you are interested or make any progress, feel free to share.
